In [1]:
import numpy as np
import pandas as pd
import csv
import random
import math

In [2]:
rawdata=pd.read_csv('Raweyedata_drop.csv')

In [22]:
df=rawdata.iloc[32:64,2:].values

In [23]:
df

array([[1025,  751],
       [1038,  754],
       [1057,  761],
       [1083,  763],
       [1106,  758],
       [1127,  754],
       [1151,  756],
       [1168,  758],
       [1212,  764],
       [1256,  769],
       [1242,  790],
       [1143,  831],
       [1054,  865],
       [ 729,  923],
       [ 650,  753],
       [ 609,  575],
       [ 611,  349],
       [ 561,  126],
       [ 149,  199],
       [ 206,  239],
       [ 259,  250],
       [ 299,  259],
       [ 323,  262],
       [ 386,  254],
       [ 433,  244],
       [ 472,  235],
       [ 530,  228],
       [ 530,  220],
       [ 537,  219],
       [ 548,  216],
       [ 557,  219],
       [ 553,  227]], dtype=int64)

In [24]:
mean_0=df.mean(axis=0)

In [25]:
mean_0_x=mean_0[0]
mean_0_x

737.625

In [26]:
mean_0_y=mean_0[1]
mean_0_y

502.21875

In [27]:
std_0=df.std(axis =0) 

In [28]:
std_0_x=std_0[0]
std_0_x

347.3208845937716

In [29]:
std_0_y=std_0[1]
std_0_y

274.1878615081957

0.1335666730800713

In [19]:
x_nor=np.zeros([32,1],dtype=int)


In [20]:
for i in range(0,32):
    r=random.random()
    x_nor[i]=mean_0_x+r*std_0_x

In [21]:
x_nor

array([[920],
       [955],
       [973],
       [921],
       [940],
       [949],
       [913],
       [921],
       [931],
       [954],
       [972],
       [945],
       [914],
       [951],
       [927],
       [911],
       [973],
       [916],
       [940],
       [937],
       [914],
       [911],
       [934],
       [927],
       [940],
       [929],
       [905],
       [970],
       [922],
       [950],
       [902],
       [962]])

In [150]:
y_nor=np.zeros([32,1],dtype=int)

In [151]:
for i in range(0,32):
    r=random.random()
    y_nor[i]=mean_0_y+r*std_0_y

In [152]:
y_nor

array([[722],
       [736],
       [736],
       [739],
       [730],
       [729],
       [731],
       [739],
       [721],
       [706],
       [705],
       [710],
       [704],
       [740],
       [742],
       [734],
       [732],
       [747],
       [708],
       [717],
       [706],
       [735],
       [733],
       [722],
       [735],
       [714],
       [746],
       [724],
       [743],
       [738],
       [745],
       [719]])

In [153]:
df_0_nor=np.append(x_nor,y_nor,axis=1)

In [154]:
df_0_nor

array([[907, 722],
       [917, 736],
       [935, 736],
       [954, 739],
       [966, 730],
       [917, 729],
       [934, 731],
       [937, 739],
       [912, 721],
       [928, 706],
       [967, 705],
       [907, 710],
       [959, 704],
       [916, 740],
       [968, 742],
       [935, 734],
       [942, 732],
       [936, 747],
       [911, 708],
       [904, 717],
       [951, 706],
       [911, 735],
       [962, 733],
       [932, 722],
       [937, 735],
       [941, 714],
       [970, 746],
       [901, 724],
       [928, 743],
       [904, 738],
       [927, 745],
       [948, 719]])

In [157]:
df_0_nor=pd.DataFrame(df_0_nor)

In [158]:
df_0_nor

0    1
0   907  722
1   917  736
2   935  736
3   954  739
4   966  730
5   917  729
6   934  731
7   937  739
8   912  721
9   928  706
10  967  705
11  907  710
12  959  704
13  916  740
14  968  742
15  935  734
16  942  732
17  936  747
18  911  708
19  904  717
20  951  706
21  911  735
22  962  733
23  932  722
24  937  735
25  941  714
26  970  746
27  901  724
28  928  743
29  904  738
30  927  745
31  948  719

0    1
0   930  720
1   908  719
2   973  727
3   925  714
4   913  709
5   957  716
6   901  733
7   922  710
8   903  734
9   906  714
10  969  734
11  915  711
12  940  703
13  958  734
14  972  716
15  937  725
16  975  707
17  907  709
18  910  721
19  953  740
20  962  721
21  956  741
22  934  742
23  924  724
24  968  737
25  959  728
26  905  719
27  938  709
28  963  727
29  942  721
30  925  725
31  933  734

In [129]:
columns[1].replace

1

In [160]:
sin(3.14/2)

NameError: name 'sin' is not defined

In [159]:
def normal_pattern(x_mean,x_std,y_mean,y_std):
    r=random.random()
    x_nor=x_mean+r*x_std
    y_nor=y_mean+r*y_std
    

In [162]:
def cyclic_pattern(x_mean,x_std,y_mean,y_std,t,T):
    PI=math.pi
    r=random.random()
    a_x=random.uniform(1.5*x_std,2.5*x_std)
    x_cyc=x_mean+r*x_std+a_x*math.sin(2*PI*t/T)
    a_y=random.uniform(1.5*y_std,2.5*y_std)
    y_cyc=y_mean+r*y_std+a_y*math.sin(2*PI*t/T)
    

In [ ]:
x_train=df.iloc[]

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import math
PI=math.pi

dataset=pd.read_csv('Raweyedata_drop.csv')

df_x=dataset.iloc[0:32,2]
df_y=dataset.iloc[0:32,3]

x_mean=df_x.mean(axis=0)
y_mean=df_y.mean(axis=0)

x_std=df_x.std(axis=0)
y_std=df_y.std(axis=0)

def normal_pattern(x_mean,x_std,y_mean,y_std):
    r=random.random()
    x1=x_mean+r*x_std
    y1=y_mean+r*y_std
    return x1,y1

def cyclic_pattern(x_mean,x_std,y_mean,y_std,t,T):
    PI=math.pi
    r=random.random()
    a_x=random.uniform(1.5*x_std,2.5*x_std)
    x2=x_mean+r*x_std+a_x*math.sin(2*PI*t/T)
    a_y=random.uniform(1.5*y_std,2.5*y_std)
    y2=y_mean+r*y_std+a_y*math.sin(2*PI*t/T)
    return x2,y2
def systematic_pattern(x_mean,x_std,y_mean,y_std,t):
    r=random.random()
    d_x=random.uniform(1*x_std,3*x_std)
    x3=x_mean+r*x_std+d_x*pow(-1,t)
    d_y=random.uniform(1*y_std,3*y_std)
    y3=y_mean+r*y_std+d_y*pow(-1,t)
    return x3,y3
def stratification_pattern(x_mean,x_std,y_mean,y_std):
    r=random.random()
    stdd_x=random.uniform(0.2*x_std,0.4*x_std)
    x4=x_mean+r*stdd_x
    stdd_y=random.uniform(0.2*y_std,0.4*y_std)
    y4=y_mean+r*stdd_y
    return x4,y4

def uptrend_pattern(x_mean,x_std,y_mean,y_std,t):
    r=random.random()
    g_x=random.uniform(0.05*x_std,0.25*x_std)
    x5=x_mean+r*x_std+t*g_x
    g_y=random.uniform(0.05*y_std,0.25*y_std)
    y5=y_mean+r*y_std+t*g_y
    return x5,y5

def downtrend_pattern(x_mean,x_std,y_mean,y_std,t):
    r=random.random()
    g_x=random.uniform(0.05*x_std,0.25*x_std)
    x6=x_mean+r*x_std-t*g_x
    g_y=random.uniform(0.05*y_std,0.25*y_std)
    y6=y_mean+r*y_std-t*g_y
    return x6,y6

def upshift_pattern(x_mean,x_std,y_mean,y_std,t):
    p=random.uniform(10,20)
    r=random.random()
    if t>=p:
        k=1
    else:
        k=0
    s_x=random.uniform(x_std,3*x_std)
    x7=x_mean+r*x_std+k*s_x
    s_y=random.uniform(y_std,3*y_std)
    y7=y_mean+r*y_std+k*s_y
    return x7,y7

def downshift_pattern(x_mean,x_std,y_mean,y_std,t):
    p=random.uniform(10,20)
    r=random.random()
    if t>=p:
        k=1
    else:
        k=0
    s_x=random.uniform(x_std,3*x_std)
    x8=x_mean+r*x_std-k*s_x
    s_y=random.uniform(y_std,3*y_std)
    y8=y_mean+r*y_std-k*s_y
    return x8,y8


x_point=np.zeros([256,1])
y_point=np.zeros([256,1])
y_train=np.zeros([256,1])

for i in range(1,9):
    for j in range(0,32):
        if i==1:   
            x_point[j],y_point[j]=normal_pattern(x_mean,x_std,y_mean,y_std)
        elif i==2:
            x_point[j+32],y_point[j+32]=cyclic_pattern(x_mean,x_std,y_mean,y_std,j+1,32)
        elif i==3:
            x_point[j+64],y_point[j+64]=systematic_pattern(x_mean,x_std,y_mean,y_std,j+1)
        elif i==4:
            x_point[j+96],y_point[j+96]=stratification_pattern(x_mean,x_std,y_mean,y_std)
        elif i==5:
            x_point[j+128],y_point[j+128]=uptrend_pattern(x_mean,x_std,y_mean,y_std,j+1)
        elif i==6:
            x_point[j+160],y_point[j+160]=downtrend_pattern(x_mean,x_std,y_mean,y_std,j+1)
        elif i==7:
            x_point[j+192],y_point[j+192]=upshift_pattern(x_mean,x_std,y_mean,y_std,j+1)
        elif i==8:
            x_point[j+224],y_point[j+224]=downshift_pattern(x_mean,x_std,y_mean,y_std,j+1)

In [6]:
x_train=np.append(x_point,y_point,axis=1)

In [9]:
x_train

array([[ 975.91735429,  747.16438231],
       [ 904.82797508,  705.29279955],
       [ 971.6542344 ,  744.65340839],
       [ 919.96129324,  714.20631083],
       [ 969.71531931,  743.51138908],
       [ 904.02364571,  704.81905024],
       [ 951.25193843,  732.63647374],
       [ 938.27775876,  724.99469315],
       [ 915.11940071,  711.35444033],
       [ 971.74857684,  744.708976  ],
       [ 969.82927801,  743.57851065],
       [ 914.22875478,  710.82985064],
       [ 945.40222343,  729.19099667],
       [ 967.9109183 ,  742.44859845],
       [ 921.58783544,  715.16434278],
       [ 922.6504053 ,  715.79019551],
       [ 912.93200011,  710.06606327],
       [ 963.87218169,  740.06978608],
       [ 936.71713763,  724.07548866],
       [ 916.02982192,  711.89067763],
       [ 909.86728128,  708.26094653],
       [ 965.35855758,  740.9452602 ],
       [ 944.66082462,  728.75431342],
       [ 935.20719522,  723.18613389],
       [ 937.28170849,  724.40802041],
       [ 957.93523802,  7